//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApPBeneficiarios.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiarios
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string curp { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int id_sexo { get; set; }
        public Nullable<int> id_telefono { get; set; }
        public Nullable<int> id_direccion { get; set; }
    
        public virtual direcciones direcciones { get; set; }
        public virtual generos generos { get; set; }
        public virtual telefonos telefonos { get; set; }
    }
}
