//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApPBeneficiarios.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdbeneficiariosEntities4 : DbContext
    {
        public bdbeneficiariosEntities4()
            : base("name=bdbeneficiariosEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<beneficiarios> beneficiarios { get; set; }
        public virtual DbSet<direcciones> direcciones { get; set; }
        public virtual DbSet<generos> generos { get; set; }
        public virtual DbSet<telefonos> telefonos { get; set; }
    }
}
